version: '3.6'
services:
  sut:
    build:
      context: .
      dockerfile: Dockerfile
      target: test


    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./pyserver:/${PROJECT}/${PACKAGE}:ro
      - ./test:/${PROJECT}/test
      - ./artifacts:/${PROJECT}/artifacts

    command:
      py.test --cov=/${PROJECT}/${PACKAGE} -vv
              --cov-report html:/${PROJECT}/artifacts/html-coverage
              --cov-report term
              --html=/server/artifacts/html-report/report.html
              /${PROJECT}/test