name: pre-commit

# Workflow for code quality checks and dependency management
# This workflow ensures code quality standards are maintained and dependencies are properly managed

on:
  push:  # Run on every push to the repository

jobs:
  # Job to run pre-commit hooks for code quality checks
  # This includes linting, formatting, and other code quality checks
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      # Run pre-commit hooks defined in .pre-commit-config.yaml
      - uses: tschm/cradle/actions/pre-commit@v0.1.68
